# Project information
site_name: bunqDesktop Wiki
site_url: https://wiki.bunqdesk.top/

# Repository
repo_name: 'bunqCommunity/bunqDesktopWiki'
repo_url: 'https://github.com/bunqCommunity/bunqDesktopWiki'

# Pages and navigation
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Setup account:
    - 'API Key': 'setup/setup-api-key.md'
    - 'OAuth': 'setup/setup-oauth.md'
  - Demo Mode:
    - 'Sandbox account explained': 'demo-mode/demo-mode.md'
    - 'Create a sandbox account': 'demo-mode/demo-mode-setup-api-key.md'
    - 'Add funds to the account': 'demo-mode/demo-mode-money.md'
  - Categories & Rules:
    - 'Categories explained': 'categories/categories.md'
    - 'Category rules explained': 'categories/category-rules.md'
    - 'Default rules & categories': 'categories/categories-rules-default.md'
  - Changing your address: 'change-address.md'
  - Data security: 'data-security.md'

# Theme settings
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Social links and other settings
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bunqCommmunity/bunqDesktopWiki'
    - type: 'link'
      link: 'https://bunqdesk.top'

google_analytics: ['UA-124732952-1', 'wiki.bunqdesk.top']
