# Project information
site_name: bunqDesktop Wiki
site_url: https://wiki.bunqdesk.top/

# Repository
repo_name: 'bunqCommunity/bunqDesktopWiki'
repo_url: 'https://github.com/bunqCommunity/bunqDesktopWiki'

# Pages and navigation
nav:
  - Home: index.md

# Theme settings
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Social links and other settings
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bunqCommmunity/bunqDesktopWiki'
    - type: 'link'
      link: 'https://bunqdesk.top'

google_analytics:
  - 'UA-124732952-1'
  - 'auto'      